# Generated by Django 4.2.6 on 2023-11-28 00:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calendarapp', '0003_alter_event_title'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventmember',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='eventmember',
            name='email',
            field=models.EmailField(default='email@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='eventmember',
            name='nickname',
            field=models.CharField(default='name', max_length=100),
        ),
        migrations.AddField(
            model_name='eventmember',
            name='role',
            field=models.CharField(default='role', max_length=100),
        ),
        migrations.AlterField(
            model_name='eventmember',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='calendarapp.event'),
        ),
        migrations.AlterUniqueTogether(
            name='eventmember',
            unique_together={('event', 'user', 'role')},
        ),
    ]
